### ISSUE TITLE
Unable to track execution of filters

### ISSUE THREAD

**Issue by Ebendiol** [reactivemarbles/DynamicData#206]
I'm currently trying to bind a busy indicator in a Mobile user interface so the user knows when we are done filtering the results on a large list of items.  

I'm able to track the start of the filtering operation through the `Observable ` via a subscription to my dynamic filter.  The issue resides in the fact that the changeset `Observable` doesn't always trigger if the filter hasn't changed anything in the results.  

The easiest example would be applying a filter that yields not results followed by another (different) filter that yields not result also.  The `Observable` will get triggered the first time but not the second time because no changes were detected (IE: we went form 0 results to 0 results... No Adds, Deletes, etc.).

This prevents me from dismissing my busy indicator in cases where the results haven't changed, I haven't been able to find a workaround.

Having the `Observable` trigger after every filtering operation regardless of the number of changes to the results would allow providing UI feedback and also give the ability to proactively track performance of sort operations as an added bonus.

Here's code that illustrates the issue:

    var disposables = new CompositeDisposable();
    var sourceList = new SourceList<string>();
    ReadOnlyObservableCollection<string> results;
    
    using (disposables)
    {
        // Create 100,000 dummy strings to start with
        sourceList.Edit(
            (innerList) =>
            {
                Enumerable
                    .Range(1, 100000)
                    .ForEach(x => innerList.Add(x.ToString()));
            });
    
        // Fake text trigger to replicate WhenAnyValue
        var trigger = new Subject<string>();
    
        disposables.Add(trigger);
    
        // Dynamic filter
        var filter = trigger                    
            .Do(s =>
            {
                Console.WriteLine($"\r\nSearching for: {s}");
            })
            .Select(
                searchTerm =>
                {
                    Func<string, bool> searcher = item => item.StartsWith(
                        searchTerm,
                        StringComparison.InvariantCultureIgnoreCase);
    
                    return searcher;
                });
    
        disposables.Add(
            sourceList
                .Connect()
                .Filter(filter)
                .Bind(out results)
                .Subscribe(
                    x =>
                    {
                        Console.WriteLine($"Got {results.Count} results");
                    }));
    
        // Those works as expected
        trigger.OnNext("99999");
        trigger.OnNext("9999");
        trigger.OnNext("9998");
        trigger.OnNext("1");
        trigger.OnNext("100001");
    
        // At this point, because there aren't any changes we don't get any more results
        // until we return something other than 0 items.
        trigger.OnNext("100002");
        trigger.OnNext("100003");
    
        // This will get results as expected.
        trigger.OnNext("99998");
    
    }

This code give the following results.. notice how I don't get any results for 100002 and 100003:

    Searching for: 99999
    Got 1 results
    
    Searching for: 9999
    Got 11 results
    
    Searching for: 9998
    Got 11 results
    
    Searching for: 1
    Got 11112 results
    
    Searching for: 100001
    Got 0 results
    
    Searching for: 100002
    
    Searching for: 100003
    
    Searching for: 99998
    Got 1 results

**Comment by RolandPheasant** [comment]
This is my priority for the next release.

**Comment by RolandPheasant** [comment]
This is in progress but is taking time because:

 - I need to ensure there is minimal performance hit with allowing empty filter results.
 - I am also removing the restriction for empty change set notifications on the source list / cache as several consumers have had the same issue as this when attempting to monitor list / cache edit changes

**Comment by ibreault** [comment]
Quick follow up, is it still on the horizon?

**Comment by RolandPheasant** [comment]
I have made some progress but the impact is substantial. Making the changes to the cache and lists resulted in 200+ broken unit tests as the lib depends heavily on the current behaviour. This is a pain but I have fixed most of them so in itself not a major problem. 

However, I have paused for now as I have also realised that a large number of internal optimisations will be invalidated by these changes. The implication is I will have to go through the code base and ensure that each operator is re-optimised. Not all operators would become sub-optimal but I would have to check everything and that would take some time.

The pause has allowed me to reflect a little on the change. I have lumped in allowing empty notification generally and not just when applying a filter as others have reported similar issues, not with filtering but with monitoring loading. Taking a step back it would be better for me to address the filter issue as a distinct task. or alternatively try and think up another solution. For example perhaps I could apply an overload to the filter observable like this:

```cs
mySourceCache
    .Filter(myFilterObservable, onApplyingCallback, OnAppliedCallback)
```

In theory this would work but not perfectly when you switch threads 

```cs
mySourceCache
    .Filter(myFilterObservable, onApplyingCallback, OnAppliedCallback)
    .ObserveOn(mainThreadScheduler) 
   .Bind(out myCollection)
```

In this case, due to the thread switch, the `OnAppliedCallback` will be invoked at the point that the thread switches i.e. before binding which means the call back takes place before rendering. Therefore I am not sure this is the best solution so I will keep on thinking...

**Comment by ibreault** [comment]
This would be a really good short term solution, it would also be a great addition to the framework.  Tracking filter execution as a lot of benefits in my opinion.

It doesn't really fix my problem per say but gives me what I need to work around the current limitations.  

If the `OnAppliedCallback` includes the `IChangeSet<T>` then I would be able to decide if I need to deal with the UI immediately because of an empty changeset or defer to my Bind observable if the changeset isn't empty.  The thread switching wouldn't be much of an issue in my case since an empty changeset wouldn't have anything to Bind and nothing would change in my UI anyway.

Does that make sense?

P.S.  Sort() would like benefit from the same type of callbacks also.

**Comment by RolandPheasant** [comment]
This one has been a long time in the making.  Finally, I decided to simply apply an opt-in to enable empty change notifications. Simple really. I have done this for the cache and the list will follow shortly.  See [#494](https://github.com/reactivemarbles/DynamicData/pull/494)

```var subscription = _source.Connect(suppressEmptyChangeSets: false)```

Using this will enable empty change notifications. I have also added the overload to filter methods.
